on: [push, pull_request]
name: Test
jobs:
  roave_bc_check:
    name: Roave BC Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Roave BC Check
        uses: docker://nyholm/roave-bc-check-ga

  test:
    runs-on: ubuntu-latest
    container:
      image: pluswerk/php-dev:nginx-${{ matrix.php[0] }}
      options: -t --user 1000 -e=APPLICATION_PATH=/__w/
    strategy:
      fail-fast: true
      matrix:
        php: [
          # ['7.2', 'v1', '^4.4.0'],
          ['7.3', 'v1', '^5.0'],
          ['7.4', 'v2', '^5.0'],
          ['8.0', 'v2', '^5.0'],
        ]
    name: PHP ${{ matrix.php[0] }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependenciess
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php[0] }}-composer-${{ hashFiles('composer.json') }}
      - name: Install dependencies for Symfony ${{ matrix.php[2] }}
        if: ${{ matrix.php[1] == 'v1' }}
        run: |
          composer1 install
          composer1 require symfony/process:${{ matrix.php[2] }} symfony/console:${{ matrix.php[2] }}
      - name: Install dependencies for Symfony ${{ matrix.php[2] }}
        if: ${{ matrix.php[1] == 'v2' }}
        run: |
          composer2 install
          composer2 require symfony/process:${{ matrix.php[2] }} symfony/console:${{ matrix.php[2] }}
      - name: Execute tests
        run: |
          vendor/bin/grumphp run
          composer test
          composer infection
          composer phpstan
      - uses: codecov/codecov-action@v1
        with:
          file: ./tests/test-results/coverage.xml
